// Make sure these exports are properly defined
export const initialStaffProfile = {
  staffCode: "",
  firstName: "",
  lastName: "",
  gender: "",
  birthday: "",
  email: "",
  phone: "",
  workplace: "",
  status: "",
  jobPosition: "",
  directManager: "",
  role: "",
  academicLevel: "",
  hourlyRate: "",
  defaultLanguage: "System Default",
  direction: "System Default",
  emailSignature: "",
  otherInformation: "",
  twilioPhoneNumber: "",
  isTwilioWhatsAppEnabled: "",
  password: "",
  enableTwoFactor: false,
  domicile: "",
  maritalStatus: "",
  currentAddress: "",
  nation: "",
  placeOfBirth: "",
  religion: "",
  citizenIdentification: "",
  dateOfIssue: "",
  placeOfIssue: "",
  resident: "",
  bankAccountNumber: "",
  bankAccountName: "",
  bankName: "",
  personalTaxCode: "",
  epfNo: "",
  socialSecurityNo: "",
  facebook: "",
  linkedin: "",
  skype: "",
}

// Ensure this sample data is properly exported
export const sampleStaffProfile = {
  id: "1",
  staffCode: "0001",
  firstName: "Ananya",
  lastName: "Sharma",
  gender: "Female",
  birthday: "1994-07-12",
  email: "talent@cybercurate.com",
  phone: "+919307059006",
  workplace: "Bengaluru Office",
  status: "Full-time",
  jobPosition: "HR Associate",
  directManager: "John Doe",
  role: "Employee",
  academicLevel: "B Sc. Graduate",
  hourlyRate: "120.00",
  defaultLanguage: "System Default",
  direction: "System Default",
  emailSignature: "",
  otherInformation: "",
  twilioPhoneNumber: "",
  isTwilioWhatsAppEnabled: "",
  password: "",
  enableTwoFactor: false,
  domicile: "",
  maritalStatus: "Married",
  currentAddress: "1/2, Half Road, Fullfield, Wonder City, Bengaluru",
  nation: "India",
  placeOfBirth: "Mumbai",
  religion: "Hindu",
  citizenIdentification: "Aadhar Card",
  dateOfIssue: "2012-05-03",
  placeOfIssue: "",
  resident: "",
  bankAccountNumber: "23498756421",
  bankAccountName: "Nallurhalli Branch",
  bankName: "State Bank of India",
  personalTaxCode: "ABCD1234",
  epfNo: "",
  socialSecurityNo: "",
  facebook: "",
  linkedin: "",
  skype: "",
}
